### PR TITLE
Request Bookings per CID 

### PR DESCRIPTION
**Pull request by enrico-marques**
Hello

I made a modification to be able to pull all the reservations linked to a CID, I missed it when I went to implement it, if you want to contact me my discord is Enrico Marques#2988

### CODE REVIEW

**Comment by zachbf** [comment]
This looks good @Enrico1108.
Any issues/comments from higher up @fixterjake ?

**Review by zachbf — APPROVED** [review]

**Comment by enrico-marques** [comment]
hello, would you have a forecast of when the PR will be approved?

@zachbf 
@fixterjake

**Comment by zachbf** [comment]
Sorry for the delay.

**Comment by enrico-marques** [comment]
OK! Thanks, one more question, for the API in production going today? @zachbf

**Pull request merged**
